applications:
  app:
    type: nodejs:20

    build:
      flavor: none

    hooks:
      build: |
        # set -xe
        npm ci
        npm run build

    web:
      commands:
        start: npm run preview -- --port=$PORT

      locations:
        /:
          root: dist
          passthru: true
          index: [index.html]

routes:
  "https://{default}/":
    type: upstream
    upstream: app:http