applications:
  app:
    type: nodejs:22

    build:
      flavor: nodejs_build

    hooks:
      build: |
        set -xe
        npm ci --omit=dev
        npm run build

    web:
      commands:
        start: npm run serve -- --port=$PORT

      locations:
        /:
          root: public
          passthru: true
          index: [index.html]
